language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - "pip install coverage --use-mirrors"
  - "pip install pep8 --use-mirrors"
  - "pip install pyflakes --use-mirrors"
  - "pip install pytest --use-mirrors"
  - "pip install requests --use-mirrors"
before_script:
  - "pep8 --show-source --show-pep8 --max-line-length=160 ."
#  - "pyflakes ."
  - export QINIU_ACCESS_KEY="QWYn5TFQsLLU1pL5MFEmX3s5DmHdUThav9WyOWOm"
  - export QINIU_SECRET_KEY="Bxckh6FA-Fbs9Yt3i3cbKVK22UPBmAOHJcL95pGz"
  - export QINIU_TEST_BUCKET="pythonsdk"
  - export QINIU_TEST_DOMAIN="pythonsdk.qiniudn.com"
  - export QINIU_TEST_ENV="travis"
  - export PYTHONPATH="$PYTHONPATH:."
script:
  - py.test
